### ISSUE TITLE
Using  vtune with pymic.

### ISSUE THREAD

**Issue by felippezacarias** [01org/pyMIC#10]
Do you have an example of profiling code offloaded using pyMIC with vTune?

**Comment by mjklemm** [comment]
Hi, 

there are no specific examples on how to use VTune Amplifier XE with pymic. If you have a working version of it installed (VTune Ampl. XE on the host, SEP driver installed on the coprocessor), then it comes down to running the workload and having VTune Amplifier XE profiling the coprocessor. You would have to use a system-wide analysis on the coprocessor. 

Hope that helps. If you need more information, please let me know.

Cheers,
        -michael
