### ISSUE TITLE
compilation for MIC does not pick up the correct libraries openMP

### ISSUE THREAD

**Issue by pvelesko** [01org/pyMIC#9]
I'm using anaconda, when compiling devito for host looks at ~/anaconda2/lib for libiomp5.so
when compiling devito for MIC it does the same.

Instead it should ask for directory containing Intel MIC libraries normally found under /opt/intel/compilers_and_libraries/something/something/lib/

**Comment by mjklemm** [comment]
Hi,

Thanks for the bug report.  I will look into this problem and come back to you.  Please stay tuned.

Kind regards,
        -michael

**Comment by mjklemm** [comment]
I have checked my Anaconda installation and there it works. Can you please share a build log with me, so that I can dig deeper into this issue?

**Comment by pvelesko** [comment]
Sorry, I just now realized that I posted this in the wrong thread. My apologies
